import HeroCarousel from '../components/HeroCarousel'
import KpiBand from '../components/KpiBand'
import { Link } from 'react-router-dom'
import { Coffee, Flag, Handshake, Landmark, Users, Wine } from 'lucide-react'

const PROGRAM_PDF =
  'https://a2m-website-git-feat-v4-full-content-andysteph21s-projects.vercel.app/program/a2m-2027-program.pdf'

function SectionEyebrow({ children }: { children: React.ReactNode }) {
  return (
    <span className="font-semibold text-[11px] uppercase tracking-[0.26em] text-copper">{children}</span>
  )
}

const experiences = [
  {
    icon: Landmark,
    title: 'Ministerial Roundtable',
    text: 'The closed-door political dialogue on June 6.',
    href: '/en/program/ministerial-roundtable',
  },
  {
    icon: Flag,
    title: 'Honorary Country',
    text: "Côte d'Ivoire, the 2027 edition's showcase.",
    href: '/en/program/honorary-country',
  },
  {
    icon: Users,
    title: 'Women in Mining Forum',
    text: "Women's leadership, from site to boardroom.",
    href: '/en/program/women-in-mining',
  },
  {
    icon: Coffee,
    title: "Investors' Breakfast",
    text: '90 closed-door minutes, capital side only.',
    href: '/en/program/investors-breakfast',
  },
  {
    icon: Handshake,
    title: 'Business Matchmaking',
    text: 'Your strategic B2B agenda, generated by AI-powered matching.',
    href: '/en/program#matchmaking',
  },
  {
    icon: Wine,
    title: 'Networking & Social Events',
    text: 'Networking evenings and the Gala — relationships that outlast the deal.',
    href: '/en/program/networking',
  },
]

export default function HomePage() {
  return (
    <>
  <HeroCarousel />
  <KpiBand
    footnote="The Canada–Africa mining relationship at a glance."
    items={[
      { value: "30%", label: "of global mineral reserves" },
      { value: "45B+", label: "Canadian investments" },
      { value: "120+", label: "TSX-listed companies active" },
      { value: "30+", label: "African mining countries" },
    ]}
  />
  <section className="a2m-reveal py-14 lg:py-16 bg-ivory">
    <div className="mx-auto w-full max-w-[1280px] px-4 sm:px-8 lg:px-16">
      <div className="mx-auto max-w-[900px] text-center">
        <span className="mx-auto mb-6 block h-0.5 w-10 rounded-full bg-gold" aria-hidden="true" />
        <h2 className="text-balance font-display font-bold text-h2 text-ink tracking-[-0.01em]">
          Unlocking Africa's Mining Potential in Montreal
        </h2>
        <p className="mt-6 text-lead text-muted leading-[1.7]">
          African Mining in Montreal (A2M) brings together the leading figures of the African mining industry in Montreal, Canada — government officials, industry visionaries, financiers, investors, and service providers — to explore Africa's vast mining potential and unlock transformative opportunities. This flagship event features keynote presentations from renowned industry thought leaders, interactive panel discussions, investment showcases and exclusive networking opportunities.
        </p>
      </div>
      <div className="mx-auto mt-10 flex max-w-[760px] flex-wrap items-start justify-center gap-x-12 gap-y-5 border-t border-hairline pt-8">
        <div className="text-center">
          <p className="font-semibold text-[10px] text-muted uppercase tracking-[0.16em]">
            Format
          </p>
          <p className="mt-1 font-display font-semibold text-[15px] text-emerald-deep">
            3 days
          </p>
        </div>
        <div className="text-center">
          <p className="font-semibold text-[10px] text-muted uppercase tracking-[0.16em]">
            B2B meetings
          </p>
          <p className="mt-1 font-display font-semibold text-[15px] text-emerald-deep">
            3,000+
          </p>
        </div>
        <div className="text-center">
          <p className="font-semibold text-[10px] text-muted uppercase tracking-[0.16em]">
            Ministerial Roundtable
          </p>
          <p className="mt-1 font-display font-semibold text-[15px] text-emerald-deep">
            June 6
          </p>
        </div>
      </div>
    </div>
  </section>
  <section className="a2m-reveal py-14 lg:py-16 relative overflow-hidden a2m-motif bg-emerald-deep">
    <div className="mx-auto w-full max-w-[1280px] px-4 sm:px-8 lg:px-16 relative z-10">
      <div className="flex flex-col gap-3 items-center text-center">
        <SectionEyebrow>The A2M model</SectionEyebrow>
        <span className="block h-0.5 w-10 rounded-full bg-gold" aria-hidden="true" />
        <h2 className="font-display font-bold tracking-[-0.01em] text-ivory">
          Three pillars
        </h2>
        <p className="max-w-[640px] text-ivory/80 mx-auto">
          The event is built on three commercial fundamentals.
        </p>
      </div>
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 mt-12">
        <div className="h-full">
          <div className="rounded-sm border transition-all duration-[250ms] ease-discret border-hairline bg-card shadow-card hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex h-full flex-col gap-3 p-6">
            <span className="tnum font-display font-bold text-data text-bronze">01</span>
            <h3 className="flex items-center gap-2.5 font-display font-semibold text-h3 text-ink">
              Invest
            </h3>
            <p className="text-body text-muted">
              Connect with high-potential projects, leading institutions, and key government decision-makers — all in one powerful platform. Gain access to a curated deal flow of vetted opportunities.
            </p>
          </div>
        </div>
        <div className="h-full">
          <div className="rounded-sm border transition-all duration-[250ms] ease-discret border-hairline bg-card shadow-card hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex h-full flex-col gap-3 p-6">
            <span className="tnum font-display font-bold text-data text-bronze">02</span>
            <h3 className="flex items-center gap-2.5 font-display font-semibold text-h3 text-ink">
              Deal
            </h3>
            <p className="text-body text-muted">
              Showcase your projects, products or services at A2M Marketplace and through high-impact, structured meetings. A2M is engineered for results — leave with real deals and concrete partnerships, not just business cards.
            </p>
          </div>
        </div>
        <div className="h-full">
          <div className="rounded-sm border transition-all duration-[250ms] ease-discret border-hairline bg-card shadow-card hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex h-full flex-col gap-3 p-6">
            <span className="tnum font-display font-bold text-data text-bronze">03</span>
            <h3 className="flex items-center gap-2.5 font-display font-semibold text-h3 text-ink">
              Decide
            </h3>
            <p className="text-body text-muted">
              Meet African Mining Ministers and Canadian government officials — plus the Honorary Country delegation. All the critical decision-makers in one room, at one time.
            </p>
          </div>
        </div>
      </div>
      <div className="mt-10 flex justify-center">
        <Link
          to="/en/program"
          className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-sm font-sans font-semibold uppercase tracking-[0.06em] transition-all duration-[250ms] ease-discret active:translate-y-px focus-visible:outline-2 focus-visible:outline-offset-2 border border-gold text-gold hover:bg-gold hover:text-anthracite focus-visible:outline-gold h-12 px-7 text-[12px]"
        >
          See the program
        </Link>
      </div>
    </div>
  </section>
  <section className="a2m-reveal py-14 lg:py-16">
    <div className="mx-auto w-full max-w-[1280px] px-4 sm:px-8 lg:px-16">
      <div className="flex flex-col gap-3">
        <SectionEyebrow>The program</SectionEyebrow>
        <span className="block h-0.5 w-10 rounded-full bg-gold" aria-hidden="true" />
        <h2 className="font-display font-bold tracking-[-0.01em] text-ink">
          Six signature experiences
        </h2>
        <p className="max-w-[640px] text-muted">
          Two days. Six ways to engage. Every detail engineered.
        </p>
      </div>
      <div className="mt-10 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {experiences.map(({ icon: Icon, title, text, href }) => (
          <Link
            key={title}
            to={href}
            className="group rounded-sm border border-hairline bg-card p-6 shadow-card transition-all duration-[250ms] ease-discret hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex flex-col gap-3"
          >
            <span className="inline-flex size-11 items-center justify-center rounded-sm bg-mist text-emerald-cta">
              <Icon className="size-5" aria-hidden="true" />
            </span>
            <h3 className="font-display font-semibold text-h3 text-ink">{title}</h3>
            <p className="text-body text-muted">{text}</p>
            <span className="mt-auto inline-flex items-center gap-1.5 pt-2 font-semibold text-emerald-cta text-small transition-colors group-hover:text-emerald-deep">
              Learn more
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-arrow-right size-4 transition-transform group-hover:translate-x-1" aria-hidden="true">
                <path d="M5 12h14" />
                <path d="m12 5 7 7-7 7" />
              </svg>
            </span>
          </Link>
        ))}
      </div>
      <div className="a2m-motif relative mt-8 flex flex-col gap-6 overflow-hidden rounded-sm bg-emerald-deep p-6 text-ivory shadow-card lg:flex-row lg:items-center lg:justify-between lg:p-10">
        <div className="relative z-10 flex max-w-[720px] flex-col gap-2">
          <span className="font-semibold text-[11px] uppercase tracking-[0.26em] text-gold">By invitation only</span>
          <h3 className="font-display font-bold text-h3 text-ivory">Ministerial Roundtable</h3>
          <p className="text-body text-ivory/80">
            The first Canada–Africa political dialogue on critical minerals — 30+ African Mining
            Ministers and the Canadian government, co-creating a bilateral framework on June 6.
          </p>
        </div>
        <Link
          to="/en/program/ministerial-roundtable"
          className="relative z-10 inline-flex flex-none items-center justify-center gap-2 whitespace-nowrap rounded-sm font-sans font-semibold uppercase tracking-[0.06em] transition-all duration-[250ms] ease-discret active:translate-y-px focus-visible:outline-2 focus-visible:outline-offset-2 gold-metallic text-anthracite hover:-translate-y-0.5 hover:brightness-105 hover:shadow-gold focus-visible:outline-anthracite h-12 px-7 text-[12px]"
        >
          Discover the Roundtable
        </Link>
      </div>
    </div>
  </section>
  <section className="a2m-reveal py-14 lg:py-16">
    <div className="mx-auto w-full max-w-[1280px] px-4 sm:px-8 lg:px-16">
      <div className="grid items-center gap-10 lg:grid-cols-2">
        <div className="flex flex-col items-start gap-5">
          <SectionEyebrow>Honorary Country</SectionEyebrow>
          <span className="block h-0.5 w-10 rounded-full bg-gold" aria-hidden="true" />
          <h2 className="font-display font-bold text-h2 text-ink tracking-[-0.01em]">
            Spotlight — Côte d&rsquo;Ivoire
          </h2>
          <p className="text-lead text-muted">
            A strategic gateway to West African mining. Côte d&rsquo;Ivoire leads a high-level
            delegation to Montréal — bringing project owners, regulators, and institutional capital
            under one roof to present its flagship projects to Canadian investors.
          </p>
          <div className="grid w-full grid-cols-2 gap-4">
            <div className="rounded-sm border border-hairline bg-card p-4 shadow-card">
              <span className="tnum block font-display font-bold text-data text-emerald-deep">
                #1
              </span>
              <span className="mt-1 block text-small text-muted">
                gold exploration ranking in West Africa
              </span>
            </div>
            <div className="rounded-sm border border-hairline bg-card p-4 shadow-card">
              <span className="tnum block font-display font-bold text-data text-emerald-deep">
                20+
              </span>
              <span className="mt-1 block text-small text-muted">
                Canadian TSX companies
              </span>
            </div>
            <div className="rounded-sm border border-hairline bg-card p-4 shadow-card">
              <span className="tnum block font-display font-bold text-data text-emerald-deep">
                58 t
              </span>
              <span className="mt-1 block text-small text-muted">
                of gold produced in 2024
              </span>
            </div>
            <div className="rounded-sm border border-hairline bg-card p-4 shadow-card">
              <span className="tnum block font-display font-bold text-data text-emerald-deep">
                100 t/yr
              </span>
              <span className="mt-1 block text-small text-muted">
                production target by 2030
              </span>
            </div>
          </div>
          <Link className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-sm font-sans font-semibold uppercase tracking-[0.06em] transition-all duration-[250ms] ease-discret active:translate-y-px disabled:pointer-events-none disabled:opacity-40 focus-visible:outline-2 focus-visible:outline-offset-2 [&_svg]:size-4 [&_svg]:shrink-0 gold-metallic text-anthracite hover:-translate-y-0.5 hover:brightness-105 hover:shadow-gold focus-visible:outline-anthracite h-12 px-7 text-[12px]" to="/en/program/honorary-country">
            Discover the Honorary Country
          </Link>
        </div>
        <figure className="flex flex-col gap-1.5">
          <div style={{ aspectRatio: '4 / 5' }} className="relative overflow-hidden rounded-sm border border-hairline bg-surface w-full">
            <img alt="West African gold mining (illustrative)" loading="lazy" decoding="async" data-nimg="fill" className="object-cover" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', color: 'transparent' }} sizes="(min-width: 1024px) 50vw, 100vw" srcSet="/images/home/cote-divoire.jpg 384w, /images/home/cote-divoire.jpg 640w, /images/home/cote-divoire.jpg 750w, /images/home/cote-divoire.jpg 828w, /images/home/cote-divoire.jpg 1080w, /images/home/cote-divoire.jpg 1200w, /images/home/cote-divoire.jpg 1920w, /images/home/cote-divoire.jpg 2048w, /images/home/cote-divoire.jpg 3840w" src="/images/home/cote-divoire.jpg" />
          </div>
          <figcaption className="text-[11px] text-subtle">
            <a href="https://commons.wikimedia.org/wiki/File:Chegga_Artisanal_Mining.jpg" target="_blank" rel="noopener noreferrer" className="underline-offset-2 transition-colors hover:text-muted hover:underline">
              Will Dossett — Wikimedia Commons
              · CC BY-SA 4.0
            </a>
          </figcaption>
        </figure>
      </div>
    </div>
  </section>
  <section className="a2m-reveal py-14 lg:py-16">
    <div className="mx-auto w-full max-w-[1280px] px-4 sm:px-8 lg:px-16">
      <div className="flex flex-col gap-3">
        <SectionEyebrow>Why A2M</SectionEyebrow>
        <span className="block h-0.5 w-10 rounded-full bg-gold" aria-hidden="true" />
        <h2 className="font-display font-bold tracking-[-0.01em] text-ink">
          Top reasons to attend
        </h2>
      </div>
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-12 mt-12">
        <div className="relative min-h-[320px] overflow-hidden rounded-sm border border-hairline shadow-card sm:col-span-2 lg:col-span-6 lg:row-span-2">
          <div className="overflow-hidden border-hairline bg-surface absolute inset-0 h-full w-full rounded-none border-0">
            <img alt="Conference plenary hall" loading="lazy" decoding="async" data-nimg="fill" className="object-cover" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', color: 'transparent' }} sizes="(min-width: 1024px) 50vw, 100vw" srcSet="/images/home/reasons-decision-makers.jpg 384w, /images/home/reasons-decision-makers.jpg 640w, /images/home/reasons-decision-makers.jpg 750w, /images/home/reasons-decision-makers.jpg 828w, /images/home/reasons-decision-makers.jpg 1080w, /images/home/reasons-decision-makers.jpg 1200w, /images/home/reasons-decision-makers.jpg 1920w, /images/home/reasons-decision-makers.jpg 2048w, /images/home/reasons-decision-makers.jpg 3840w" src="/images/home/reasons-decision-makers.jpg" />
          </div>
          <div aria-hidden="true" className="absolute inset-0 bg-gradient-to-t from-emerald-deep/95 via-emerald-deep/45 to-emerald-deep/10" />
          <div className="absolute inset-x-0 bottom-0 flex flex-col gap-3 p-6 lg:p-8">
            <span className="tnum font-bold font-display text-data text-gold">
              01
            </span>
            <h3 className="font-display font-semibold text-h3 text-ivory">
              Meet the Decision-Makers
            </h3>
            <p className="max-w-[480px] text-ivory/85 text-small">
              Network with 30+ African Mining Ministers, Canadian government officials, TSX, TSX-V, and other major securities-listed mining companies CEOs, and development finance institution leaders.
            </p>
          </div>
        </div>
        <div className="a2m-motif relative flex flex-col items-start justify-center gap-1.5 overflow-hidden rounded-sm bg-emerald-deep p-6 text-ivory shadow-card lg:col-span-3">
          <span className="tnum relative z-10 font-bold font-display text-champagne text-data-xl">
            30+
          </span>
          <span className="relative z-10 font-semibold text-[11px] text-ivory/80 uppercase tracking-[0.18em]">
            African Ministers
          </span>
        </div>
        <div className="rounded-sm border transition-all duration-[250ms] ease-discret border-hairline bg-card shadow-card hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex h-full flex-col gap-3 p-6 lg:col-span-3">
          <span className="tnum font-bold font-display text-data text-gold">
            02
          </span>
          <h3 className="font-display font-semibold text-h3 text-ink">
            Build Your Pipeline
          </h3>
          <p className="text-body text-muted">
            The Investment Showcase presents pre-screened African projects to investors. Capital Markets Lounge offers private negotiation space. A2M AI-powered matching generates your strategic B2B agenda.
          </p>
        </div>
        <div className="rounded-sm transition-all duration-[250ms] ease-discret border-2 border-gold bg-card shadow-card hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex h-full flex-col overflow-hidden sm:col-span-2 lg:col-span-6">
          <div style={{ aspectRatio: '16 / 9' }} className="relative overflow-hidden border-hairline bg-surface w-full rounded-none border-0">
            <img alt="Raw gold ore in quartz" loading="lazy" decoding="async" data-nimg="fill" className="object-cover" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', color: 'transparent' }} sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" srcSet="/images/home/reasons-cote-divoire.jpg 256w, /images/home/reasons-cote-divoire.jpg 384w, /images/home/reasons-cote-divoire.jpg 640w, /images/home/reasons-cote-divoire.jpg 750w, /images/home/reasons-cote-divoire.jpg 828w, /images/home/reasons-cote-divoire.jpg 1080w, /images/home/reasons-cote-divoire.jpg 1200w, /images/home/reasons-cote-divoire.jpg 1920w, /images/home/reasons-cote-divoire.jpg 2048w, /images/home/reasons-cote-divoire.jpg 3840w" src="/images/home/reasons-cote-divoire.jpg" />
          </div>
          <div className="flex flex-1 flex-col gap-3 p-6">
            <span className="tnum font-bold font-display text-data text-gold">
              03
            </span>
            <h3 className="font-display font-semibold text-h3 text-ink">
              Discover Côte d'Ivoire
            </h3>
            <p className="text-body text-muted">
              Explore the #1 gold exploration destination in West Africa. 20+ Canadian TSX mining and companies already operating. 58 tonnes of gold produced in 2024. Target: 100 tonnes/year by 2030.
            </p>
          </div>
        </div>
        <div className="rounded-sm border transition-all duration-[250ms] ease-discret border-hairline bg-card shadow-card hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex h-full flex-col gap-3 p-6 lg:col-span-4">
          <span className="tnum font-bold font-display text-data text-gold">
            04
          </span>
          <h3 className="font-display font-semibold text-h3 text-ink">
            Shape the Future
          </h3>
          <p className="text-body text-muted">
            Co-create the first bilateral Canada-Africa political instrument on critical minerals — alongside 30 African ministers and the Canadian government.
          </p>
        </div>
        <div className="rounded-sm border transition-all duration-[250ms] ease-discret border-hairline bg-card shadow-card hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex h-full flex-col gap-3 p-6 lg:col-span-4">
          <span className="tnum font-bold font-display text-data text-gold">
            05
          </span>
          <h3 className="font-display font-semibold text-h3 text-ink">
            Access African Capital
          </h3>
          <p className="text-body text-muted">
            Meet key African bankers and financiers — the institutions co-financing Africa's next generation of mines.
          </p>
        </div>
        <div className="rounded-sm border transition-all duration-[250ms] ease-discret border-hairline bg-card shadow-card hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex h-full flex-col gap-3 p-6 lg:col-span-4">
          <span className="tnum font-bold font-display text-data text-gold">
            06
          </span>
          <h3 className="font-display font-semibold text-h3 text-ink">
            Leverage the Diplomatic Platform
          </h3>
          <p className="text-body text-muted">
            A2M's ministerial structure means your investment conversations happen within a framework that reduces political and regulatory risk — on both sides of the Atlantic.
          </p>
        </div>
      </div>
      <div className="mt-10 flex flex-wrap items-center justify-between gap-6 rounded-sm border border-hairline bg-card p-6 shadow-card sm:flex-row sm:items-center">
        <div className="max-w-[560px]">
          <h3 className="font-display font-semibold text-h3 text-ink">Download the A2M 2027 program</h3>
          <p className="mt-1 text-small text-muted">
            Keynotes, panels, roundtables and the three-day agenda — the full program in one document.
          </p>
        </div>
        <a href={PROGRAM_PDF} className="inline-flex flex-none items-center justify-center gap-2 whitespace-nowrap rounded-sm font-sans font-semibold uppercase tracking-[0.06em] transition-all duration-[250ms] ease-discret active:translate-y-px focus-visible:outline-2 focus-visible:outline-offset-2 gold-metallic text-anthracite hover:-translate-y-0.5 hover:brightness-105 hover:shadow-gold focus-visible:outline-anthracite h-12 px-7 text-[12px]">
          Download the program
        </a>
      </div>
      <div className="mt-10 flex justify-start">
        <Link className="group inline-flex items-center gap-1.5 font-semibold transition-colors text-emerald-cta hover:text-emerald-deep" to="/en/news#sign-up">
          Join the waitlist
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-arrow-right size-4 transition-transform group-hover:translate-x-1" aria-hidden="true">
            <path d="M5 12h14" />
            <path d="m12 5 7 7-7 7" />
          </svg>
        </Link>
      </div>
    </div>
  </section>
  <section className="a2m-reveal py-14 lg:py-16 relative overflow-hidden a2m-motif-light bg-surface">
    <div className="mx-auto w-full max-w-[1280px] px-4 sm:px-8 lg:px-16 relative z-10">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div className="flex flex-col gap-3">
          <SectionEyebrow>News</SectionEyebrow>
          <span className="block h-0.5 w-10 rounded-full bg-gold" aria-hidden="true" />
          <h2 className="font-display font-bold tracking-[-0.01em] text-ink">
            Latest announcements
          </h2>
          <p className="max-w-[640px] text-muted">
            Announcements and media coverage around A2M 2027.
          </p>
        </div>
        <Link className="group inline-flex shrink-0 items-center gap-1.5 font-semibold transition-colors text-emerald-cta hover:text-emerald-deep" to="/en/news">
          See all news
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-arrow-right size-4 transition-transform group-hover:translate-x-1" aria-hidden="true">
            <path d="M5 12h14" />
            <path d="m12 5 7 7-7 7" />
          </svg>
        </Link>
      </div>
      <div className="mt-10">
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          <div className="rounded-sm border transition-all duration-[250ms] ease-discret border-hairline bg-card shadow-card hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex flex-col overflow-hidden p-0">
            <div style={{ aspectRatio: '16 / 9' }} className="relative overflow-hidden border-hairline bg-surface w-full rounded-none border-0">
              <img alt="Visual: community impact" loading="lazy" decoding="async" data-nimg="fill" className="object-cover" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', color: 'transparent' }} sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" srcSet="/images/news/sustainability-pledge.jpg 256w, /images/news/sustainability-pledge.jpg 384w, /images/news/sustainability-pledge.jpg 640w, /images/news/sustainability-pledge.jpg 750w, /images/news/sustainability-pledge.jpg 828w, /images/news/sustainability-pledge.jpg 1080w, /images/news/sustainability-pledge.jpg 1200w, /images/news/sustainability-pledge.jpg 1920w, /images/news/sustainability-pledge.jpg 2048w, /images/news/sustainability-pledge.jpg 3840w" src="/images/news/sustainability-pledge.jpg" />
            </div>
            <div className="flex flex-1 flex-col gap-3 p-6">
              <div className="flex flex-wrap items-center gap-2">
                <span className="inline-flex items-center rounded-sm px-[9px] py-1 font-sans font-bold text-[9px] uppercase tracking-[0.14em] bg-anthracite/8 text-muted">
                  Internal
                </span>
                <span className="text-small text-subtle">
                  ESG
                  ·
                  November 18, 2026
                </span>
              </div>
              <h3 className="font-display font-semibold text-h3 text-ink">
                Sustainability Program: up to 10% of revenues pledged
              </h3>
              <p className="text-body text-muted">
                A2M directs a share of its revenues to children's education and women's empowerment across Africa.
              </p>
              <div className="mt-auto pt-2">
                <a className="inline-flex items-center gap-1.5 font-semibold text-emerald-cta text-small transition-colors hover:text-emerald-deep" href="#">
                  Read more
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-arrow-right size-4" aria-hidden="true">
                    <path d="M5 12h14" />
                    <path d="m12 5 7 7-7 7" />
                  </svg>
                </a>
              </div>
            </div>
          </div>
          <div className="rounded-sm border transition-all duration-[250ms] ease-discret border-hairline bg-card shadow-card hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex flex-col overflow-hidden p-0">
            <div style={{ aspectRatio: '16 / 9' }} className="relative overflow-hidden border-hairline bg-surface w-full rounded-none border-0">
              <img alt="Visual: Women in Mining Forum" loading="lazy" decoding="async" data-nimg="fill" className="object-cover" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', color: 'transparent' }} sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" srcSet="/images/news/women-in-mining-programme.jpg 256w, /images/news/women-in-mining-programme.jpg 384w, /images/news/women-in-mining-programme.jpg 640w, /images/news/women-in-mining-programme.jpg 750w, /images/news/women-in-mining-programme.jpg 828w, /images/news/women-in-mining-programme.jpg 1080w, /images/news/women-in-mining-programme.jpg 1200w, /images/news/women-in-mining-programme.jpg 1920w, /images/news/women-in-mining-programme.jpg 2048w, /images/news/women-in-mining-programme.jpg 3840w" src="/images/news/women-in-mining-programme.jpg" />
            </div>
            <div className="flex flex-1 flex-col gap-3 p-6">
              <div className="flex flex-wrap items-center gap-2">
                <span className="inline-flex items-center rounded-sm px-[9px] py-1 font-sans font-bold text-[9px] uppercase tracking-[0.14em] bg-anthracite/8 text-muted">
                  Internal
                </span>
                <span className="text-small text-subtle">
                  Event
                  ·
                  November 5, 2026
                </span>
              </div>
              <h3 className="font-display font-semibold text-h3 text-ink">
                Women in Mining Forum program announced
              </h3>
              <p className="text-body text-muted">
                Keynotes, panels and networking dedicated to women's leadership in mining across Canada and Africa.
              </p>
              <div className="mt-auto pt-2">
                <a className="inline-flex items-center gap-1.5 font-semibold text-emerald-cta text-small transition-colors hover:text-emerald-deep" href="#">
                  Read more
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-arrow-right size-4" aria-hidden="true">
                    <path d="M5 12h14" />
                    <path d="m12 5 7 7-7 7" />
                  </svg>
                </a>
              </div>
            </div>
          </div>
          <div className="rounded-sm border transition-all duration-[250ms] ease-discret border-hairline bg-card shadow-card hover:-translate-y-1 hover:border-gold hover:shadow-card-hover flex flex-col overflow-hidden p-0">
            <div style={{ aspectRatio: '16 / 9' }} className="relative overflow-hidden border-hairline bg-surface w-full rounded-none border-0">
              <img alt="Visual: project showcase" loading="lazy" decoding="async" data-nimg="fill" className="object-cover" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', color: 'transparent' }} sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" srcSet="/images/news/investment-showcase-call.jpg 256w, /images/news/investment-showcase-call.jpg 384w, /images/news/investment-showcase-call.jpg 640w, /images/news/investment-showcase-call.jpg 750w, /images/news/investment-showcase-call.jpg 828w, /images/news/investment-showcase-call.jpg 1080w, /images/news/investment-showcase-call.jpg 1200w, /images/news/investment-showcase-call.jpg 1920w, /images/news/investment-showcase-call.jpg 2048w, /images/news/investment-showcase-call.jpg 3840w" src="/images/news/investment-showcase-call.jpg" />
            </div>
            <div className="flex flex-1 flex-col gap-3 p-6">
              <div className="flex flex-wrap items-center gap-2">
                <span className="inline-flex items-center rounded-sm px-[9px] py-1 font-sans font-bold text-[9px] uppercase tracking-[0.14em] bg-anthracite/8 text-muted">
                  Internal
                </span>
                <span className="text-small text-subtle">
                  Investment
                  ·
                  October 20, 2026
                </span>
              </div>
              <h3 className="font-display font-semibold text-h3 text-ink">
                Investment Showcase opens its call for projects
              </h3>
              <p className="text-body text-muted">
                Pre-screened African mining projects will be presented to institutional investors and DFIs.
              </p>
              <div className="mt-auto pt-2">
                <a className="inline-flex items-center gap-1.5 font-semibold text-emerald-cta text-small transition-colors hover:text-emerald-deep" href="#">
                  Read more
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-arrow-right size-4" aria-hidden="true">
                    <path d="M5 12h14" />
                    <path d="m12 5 7 7-7 7" />
                  </svg>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section className="a2m-motif relative overflow-hidden bg-emerald-cta text-ivory">
    <div className="mx-auto w-full max-w-[1280px] px-4 sm:px-8 lg:px-16 relative z-10 flex flex-col items-start gap-6 py-14 lg:flex-row lg:items-center lg:justify-between">
      <div className="max-w-[640px]">
        <span className="font-semibold text-[11px] uppercase tracking-[0.26em] text-gold">Limited access</span>
        <h2 className="mt-2 font-display font-bold text-h2 text-ivory">
          Founding Delegate passes are limited
        </h2>
        <p className="mt-3 text-lead text-mist/90">
          One pass. Two days. Access to everything — Investment Showcase, Matchmaking, Capital
          Markets Lounge, Ministerial Roundtable highlights, Networking Evenings and the Gala.
          Seating is limited to keep the room exclusive.
        </p>
      </div>
      <div className="flex flex-wrap gap-4">
        <Link to="/en/news#sign-up" className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-sm font-sans font-semibold uppercase tracking-[0.06em] transition-all duration-[250ms] ease-discret active:translate-y-px focus-visible:outline-2 focus-visible:outline-offset-2 gold-metallic text-anthracite hover:-translate-y-0.5 hover:brightness-105 hover:shadow-gold focus-visible:outline-anthracite h-14 px-9 text-[13px]">
          Join the waitlist
        </Link>
      </div>
    </div>
  </section>
    </>
  )
}
