// Generated by tools/build-persona-data.mjs from the archived home snapshot.
// "Who's in the room" persona tabs: section header + trigger icons/labels.
import type { ReactNode } from 'react'

export const personaSectionClassName = "a2m-reveal py-14 lg:py-16 relative overflow-hidden a2m-motif bg-emerald-deep text-ivory"

export function PersonaSectionHeader() {
  return (
  <div className="flex flex-col gap-3">
    <span className="font-semibold text-[11px] text-gold uppercase tracking-[0.26em]">
      Who's in the room
    </span>
    <h2 className="font-display font-bold text-h2 text-ivory tracking-[-0.01em]">
      Every decision-maker in the same room
    </h2>
    <p className="max-w-[640px] text-champagne/85 text-lead">
      Whatever your profile, A2M offers direct access to the decision-makers, capital and opportunities of African mining.
    </p>
  </div>
  )
}

export type PersonaTab = { id: string; label: string; icon: ReactNode }

export const personaTabs: PersonaTab[] = [
  {
    id: "majors",
    label: "Majors & mid-tiers",
    icon: (
      <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" className="size-4 shrink-0">
        <g fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M4.979 9.685C2.993 8.891 2 8.494 2 8s.993-.89 2.979-1.685l2.808-1.123C9.773 4.397 10.767 4 12 4s2.227.397 4.213 1.192l2.808 1.123C21.007 7.109 22 7.506 22 8s-.993.89-2.979 1.685l-2.808 1.124C14.227 11.603 13.233 12 12 12s-2.227-.397-4.213-1.191z" />
          <path strokeLinecap="round" d="M22 12s-.993.89-2.979 1.685l-2.808 1.124C14.227 15.603 13.233 16 12 16s-2.227-.397-4.213-1.191L4.98 13.685C2.993 12.891 2 12 2 12m20 4s-.993.89-2.979 1.685l-2.808 1.124C14.227 19.603 13.233 20 12 20s-2.227-.397-4.213-1.192L4.98 17.685C2.993 16.891 2 16 2 16" />
        </g>
      </svg>
    ),
  },
  {
    id: "juniors",
    label: "Juniors & exploration",
    icon: (
      <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" className="size-4 shrink-0">
        <g fill="none" stroke="currentColor" strokeWidth="1.5">
          <circle cx="12" cy="12" r="10" />
          <path d="M13.024 14.56c-2.31.924-3.465 1.386-4.124.938a1.5 1.5 0 0 1-.398-.398c-.448-.66.014-1.814.938-4.124c.197-.493.295-.74.465-.933q.065-.074.139-.138c.193-.17.44-.268.932-.465c2.31-.924 3.464-1.386 4.124-.938a1.5 1.5 0 0 1 .398.398c.448.66-.014 1.814-.938 4.124c-.197.493-.296.739-.465.932a2 2 0 0 1-.139.139c-.193.17-.44.268-.932.465Z" />
        </g>
      </svg>
    ),
  },
  {
    id: "investors",
    label: "Investors & DFIs",
    icon: (
      <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" className="size-4 shrink-0">
        <g fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M2 11c0-2.828 0-4.243.879-5.121C3.757 5 5.172 5 8 5h5c2.828 0 4.243 0 5.121.879C19 6.757 19 8.172 19 11s0 4.243-.879 5.121C17.243 17 15.828 17 13 17H8c-2.828 0-4.243 0-5.121-.879C2 15.243 2 13.828 2 11Z" />
          <path d="M19 8.076c.975.096 1.631.313 2.121.803c.88.878.88 2.293.88 5.121s0 4.243-.88 5.121c-.878.88-2.293.88-5.12.88h-5c-2.83 0-4.244 0-5.122-.88c-.49-.49-.707-1.146-.803-2.121" />
          <path d="M13 11a2.5 2.5 0 1 1-5 0a2.5 2.5 0 0 1 5 0Z" />
          <path strokeLinecap="round" d="M16 13V9M5 13V9" />
        </g>
      </svg>
    ),
  },
  {
    id: "services",
    label: "Services & tech",
    icon: (
      <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" className="size-4 shrink-0">
        <g fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M7 10c0-1.414 0-2.121.44-2.56C7.878 7 8.585 7 10 7h4c1.414 0 2.121 0 2.56.44c.44.439.44 1.146.44 2.56v4c0 1.414 0 2.121-.44 2.56c-.439.44-1.146.44-2.56.44h-4c-1.414 0-2.121 0-2.56-.44C7 16.122 7 15.415 7 14z" />
          <path d="M4 12c0-3.771 0-5.657 1.172-6.828S8.229 4 12 4s5.657 0 6.828 1.172S20 8.229 20 12s0 5.657-1.172 6.828S15.771 20 12 20s-5.657 0-6.828-1.172S4 15.771 4 12Z" />
          <path strokeLinecap="round" d="M4 12H2m20 0h-2M4 9H2m20 0h-2M4 15H2m20 0h-2m-8 5v2m0-20v2M9 20v2M9 2v2m6 16v2m0-20v2" />
        </g>
      </svg>
    ),
  },
  {
    id: "governments",
    label: "Governments & ministries",
    icon: (
      <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" className="size-4 shrink-0">
        <g fill="none" stroke="currentColor" strokeWidth="1.5">
          <path strokeLinecap="round" d="M22 22H2" />
          <path d="M17 22V6c0-1.886 0-2.828-.586-3.414S14.886 2 13 2h-2c-1.886 0-2.828 0-3.414.586S7 4.114 7 6v16m14 0V11.5c0-1.405 0-2.107-.337-2.611a2 2 0 0 0-.552-.552C19.607 8 18.904 8 17.5 8M3 22V11.5c0-1.405 0-2.107.337-2.611a2 2 0 0 1 .552-.552C4.393 8 5.096 8 6.5 8" />
          <path strokeLinecap="round" d="M12 22v-3M10 5h4m-4 3h4m-4 3h4m-4 3h4" />
        </g>
      </svg>
    ),
  },
  {
    id: "buyers",
    label: "Buyers & traders",
    icon: (
      <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" className="size-4 shrink-0">
        <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="1.5" d="m15.578 3.382l2 1.05c2.151 1.129 3.227 1.693 3.825 2.708C22 8.154 22 9.417 22 11.942v.117c0 2.524 0 3.787-.597 4.801c-.598 1.015-1.674 1.58-3.825 2.709l-2 1.049C13.822 21.539 12.944 22 12 22s-1.822-.46-3.578-1.382l-2-1.05c-2.151-1.129-3.227-1.693-3.825-2.708C2 15.846 2 14.583 2 12.06v-.117c0-2.525 0-3.788.597-4.802c.598-1.015 1.674-1.58 3.825-2.708l2-1.05C10.178 2.461 11.056 2 12 2s1.822.46 3.578 1.382ZM21 7.5L12 12m0 0L3 7.5m9 4.5v9.5" />
      </svg>
    ),
  },
]
